version: '3.6'

services:
  mysql:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=members
    volumes: 
      - data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    command:
      - mysqld 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  mysql-test:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=members
    volumes: 
      - test-data:/var/lib/mysql
    command:
      - mysqld 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    
  bookings:
    image: willnotwish/ruby-node:2.7.1
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=1
      - DATABASE_HOST=mysql
      - DATABASE_NAME=members
      - DATABASE_PASSWORD=root
      - DATABASE_USERNAME=root
    stdin_open: true
    tty: true
    working_dir: /app
    user: nick
    volumes:
      - .:/app
      - bundle-cache:/usr/local/bundle
    ports:
      - 3052:3000
    depends_on: 
      - mysql
    command:
      - bundle 
      - exec
      - rails
      - s 
      - -b
      - 0.0.0.0

  test: 
    image: willnotwish/ruby-node:2.7.1
    environment:
      - RAILS_ENV=test
      - RAILS_LOG_TO_STDOUT=1
      - DATABASE_HOST=mysql-test
      - DATABASE_NAME=members
      - DATABASE_PASSWORD=root
      - DATABASE_USERNAME=root
    stdin_open: true
    tty: true
    working_dir: /app
    user: nick
    volumes:
      - .:/app
      - bundle-cache:/usr/local/bundle
    depends_on: 
      - mysql-test
    command:
      - bash

volumes:
  data:
  test-data:
  bundle-cache:
