# Use mysql for all environments

default: &default
  adapter: mysql2
  database: '<%= ENV['DATABASE_NAME'] %>'
  username: '<%= ENV['DATABASE_USERNAME'] || 'root' %>'
  password: '<%= ENV['DATABASE_PASSWORD'] || 'root' %>'
  host: '<%= ENV['DATABASE_HOST'] || 'localhost' %>'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
