default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  members_login_path: <%= ENV['MEMBERS_LOGIN_PATH'] || '/login' %>
  members_logout_path: <%= ENV['MEMBERS_LOGOUT_PATH'] || '/logout' %>

development:
  <<: *default

test:
  <<: *default
  secret_key_base: 5a37811464e7d378488b0f073e2193b093682e4e21f5d6f3ae0a4e1781e61a351fdc878a843424e81c73fb484a40d23f92c8dafac4870e74ede6e5e174423010

production:
  <<: *default
